### ISSUE TITLE
Crash upon trying to open and loot minecart with chests

### ISSUE THREAD

**Issue by bugrilyus** [Magistu/Epic-Knights#10]
### Steps to Reproduce

Modlist is in the zip along with crash reports and the logs. 

Try to open minecart with chests.
Game crashes upon right clicking to open the minecart with chest and loot what is inside.
When reloaded and tried to loot again, chest opens and it has nothing inside.

[444.zip](https://github.com/Magistu/Epic-Knights/files/12027903/444.zip)

### Expected Behavior

Minecart with chests to open and generate loot

### Actual Behavior

Game freezes and crashes and gives an empty chest when reloaded where left off

### Your Minecraft version

1.20.1 Forge

### Your error log

<script src="https://gist.github.com/bugrilyus/462a4667a2097fe02c92a1617cbe963f.js"></script>

### Additional Comments

People at curseforge discord told me that it is probably about farmer's delight when I first shared them the crash reports, then they asked for the logs. After sharing the logs they said that it is related to epic knights and I should report it here.

### Conclusion

- [X] I agree that I am inattentively reading the description, just filling out everything

**Comment by Magistu** [comment]
farmer's delight mod causes the issue
