### ISSUE TITLE
Typo in naming .

### ISSUE THREAD

**Issue by Cursedth** [Magistu/Epic-Knights#11]
### Steps to Reproduce

targe is spelled as target in  magistruarmory:wood_target

Looks like more are.

version: [1.20.1-forge]-Epic-Knights-8.1.jar

### Expected Behavior

na

### Actual Behavior

na

### Your Minecraft version

1.20.1

### Your error log

na

### Conclusion

- [X] I agree that I am inattentively reading the description, just filling out everything

**Comment by Magistu** [comment]
I can't change the ids since it will lead all the weapons stored in the world to be deleted. So I won't fix that.
Although the latest version have got some other naming typos like %1$f% armor piercing which are going to be fixed very soon
