### ISSUE TITLE
ori zh_cn.json have some bug,this my ttranslation

### ISSUE THREAD

**Issue by wherephoebe** [Magistu/Epic-Knights#14]
### Steps to Reproduce

[zh_cn.txt](https://github.com/Magistu/Epic-Knights/files/12447205/zh_cn.txt)

### Expected Behavior

something

### Actual Behavior

display " ???  "

### Your Minecraft version

Minecraft 1.18.2 Forge

### Your error log

null

### Conclusion

- [X] I agree that I am inattentively reading the description, just filling out everything

**Comment by Magistu** [comment]
was fixed
