### ISSUE TITLE
Textures bugged with OptiFine in 1.20.1

### ISSUE THREAD

**Issue by Scydus** [Magistu/Epic-Knights#17]
### Steps to Reproduce

1. Install Epic Knights and the required dependencies (Cloth Config and Architectury)
2. Put OptiFine (Any Minecraft 1.20.1 compatible version) into the mods folder.
3. Launch the game, enter a world and wear some head armor from the mod, the textures will be bugged.
![EKBug](https://github.com/Magistu/Epic-Knights/assets/147647073/a3bfe9f3-a49c-45d5-9550-5eaa88966dc9)

### Expected Behavior

The textures are meant to not look weird

### Actual Behavior

The textures look weird

### Your Minecraft version

Minecraft 1.20.1 Forge 47.1.3

### Your error log

-

### Additional Comments

I attempted to mess around in video settings to no avail, reinstalled both OptiFine (several different but compatible to 1.20.1 versions) and all the mods (also all different but compatible 1.20.1 versions), and the issue always remains.
The textures work completely fine without OptiFine. Every helmet from the mod suffers from this issue. Any other modded armor packs I've tested out with OptiFine work perfectly, so I'm assuming the mod is the culprit.

Issue may be related to the headgear having the visors poke out from the player's head.

I looked through descriptions of the mod and didn't see a "not compatible with OptiFine" warning anywhere, so if there is one, I apologize for wasting time.

### Conclusion

- [ ] I agree that I am inattentively reading the description, just filling out everything

**Comment by Magistu** [comment]
For whatever reason Optifine refuses to load models registered via initializeClient. This is the common way for letting forge understand what the model does the armor have. I used to do it all the time until 1.20.1 and there were always no issues with it. I checked out some other mods and figured out that if the mod uses mixin with the armorRender override it works fine, otherwise - not. However, it's not safe to use mixin in wherever you can do without them. So I close this issue since I believe it's on optifine side

**Comment by Scydus** [comment]
> For whatever reason Optifine refuses to load models registered via initializeClient. This is the common way for letting forge understand what the model does the armor have. I used to do it all the time until 1.20.1 and there were always no issues with it. I checked out some other mods and figured out that if the mod uses mixin with the armorRender override it works fine, otherwise - not. However, it's not safe to use mixin in wherever you can do without them. So I close this issue since I believe it's on optifine side

Thanks for clarifying and replying. OptiFine sucks balls.
