### ISSUE TITLE
[1.20.1 Forge] Crash upon striking a zombie that has a shield

### ISSUE THREAD

**Issue by MrKashew** [Magistu/Epic-Knights#19]
### Steps to Reproduce

[crash-2023-10-30_11.28.27-client.txt](https://github.com/Magistu/Epic-Knights/files/13208644/crash-2023-10-30_11.28.27-client.txt)
Have yet to try on an updated Epic Knights version - will be trying now and close if it fixes / can't reproduce any longer

### Expected Behavior

No crash

### Actual Behavior

Crash

### Your Minecraft version

1.20.1

### Your error log

[crash-2023-10-30_11.28.27-client.txt](https://github.com/Magistu/Epic-Knights/files/13208644/crash-2023-10-30_11.28.27-client.txt)

### Conclusion

- [ ] I agree that I am inattentively reading the description, just filling out everything

**Comment by Magistu** [comment]
you should update the mod to a newest version
