### ISSUE TITLE
Game crashes every time I spawn in

### ISSUE THREAD

**Issue by TheBionicFish** [Magistu/Epic-Knights#2]
Every time I try to open my world which has a decent amount of progress in it, it crashes with this error (I'm running version [1.18.2-forge]-Epic-Knights-7.11.jar):

The game crashed whilst rendering entity in world
Error: net.minecraft.ResourceLocationException: Non [a-z0-9_.-] character in namespace of location: textures/models/armor/magistuarmory:rustedchainmail_layer_2.png

Thanks :)

**Comment by itzme1on** [comment]
can you send full log, please?

**Comment by TheBionicFish** [comment]
> can you send full log, please?

Here you go:
[https://pastebin.com/NCPBtFGY](url)

**Comment by itzme1on** [comment]
does minecraft work if you leave only this mod?

**Comment by TheBionicFish** [comment]
> does minecraft work if you leave only this mod?

Yes the mod works fine by itself. Sorry for the very late reply. I imagine your busy but any ideas on what caused this would be appreciated.

**Comment by itzme1on** [comment]
send your mod list, please

**Comment by itzme1on** [comment]
In general, the error occurs due to the fact that the path to the texture contains a character that the file system does not support, in your case it is `:`.
I believe this is due to some other mod.

**Comment by TheBionicFish** [comment]
List of mods I used below, I am just using the most recent version of each.
Here is a crash report the bug generated: https://pastebin.com/e8QxLkQN
It is most likely an incompatibility since I made a copy of the world, tested it, it still crashed almost as soon as it finished loading so I removed Epic Knights, tried the world again and it worked fine with nothing crashing. After re-activating the mod, I could join the world again without crashing by my weapons and armour from the mod was of course gone. I am no programmer but it seems like it is a specific item causing this bug. Thanks!

AI Improvements
Alex's Mobs
Architectury API (Fabric/Forge)
Artifacts
ATO - All the Ores
Balm (Forge Edition)
Better Combat [Fabric & Forge]
Better Ping Display
Blueprint
Citadel
Cloth Config API (Fabric/Forge)
Clumps
Configured
Creeper Overhaul
Curios API (Forge)
DataPack Anvil
Dungeon Crawl
Dusk[Forge/Fabric]
Epic Knights: Shields, Armor and Weapons [Fabr
ESSENTIAL Mod
ExpandAbility
Extra Armor
Feature NBT Deadlock Be Gone
Fog Overrides [Forge]
Framework
Galosphere
GeckoLib
GraveStone Mod
Just Enough Items (JEI)
Loot Integrations[Forge/Fabric]
Mowzie's Mobs
Not Enough Crashes (Forge)
Oh The Biomes You'll Go
Patchouli
playerAnimator
Repurposed Structures (Forge)
Rotten Creatures
Rubidium
Rubidium Extra
Savage & Ravage
Stalwart Dungeons
TerraBlender (Forge)
TexTrue's Rubidium Options
Towns and Towers
Valhelsia Core
Valhelsia Structures
Variant Tools and Weaponry - Tools and Swords
Waystones
When Dungeons Arise - Forge!
Xaero's Minimap
Xaero's World Map
YDM's MobHealthBar
YDM's Spellswords
YDM's WeirdMobs
YUNG's API (Forge)
YUNG's Better Desert Temples (Forge)
YUNG's Better Dungeons (Forge)
YUNG's Better Mineshafts (Forge)
YUNG's Better Ocean Monuments (Forge)
YUNG's Better Strongholds (Forge)
YUNG's Bridges (Forge)
YUNG's Extras (Forge)

**Comment by Lycanic** [comment]
Hi, I'm also getting this error running the Medieval MC [FORGE] - MMC3 pack (which I admit does have a lot of mods!)

To add specifics:
The error is clientside and does not affect the server.
The error appears to solely occur in deserts.
If another player can get in range of loading to force despawn of the mob (ie be at least 128 blocks away), they are not affected and the mob is removed, allowing the original player to continue playing.

Current testing:
I've made a singleplayer world with just this mod, teleported to a desert and stopped time at night. I'm allowing it to accumulate time spent in world (as I believe it may be local difficulty dependent too from my experiences).

The colon is weird, but sadly this is the only mod name in the error list so is the first port of call! If my testing doesn't result in a crash in the next few hours I will let you know and start testing other mod combinations.

**Comment by Lycanic** [comment]
As an update, I've noticed in the logs other skipped errors referring to modname:item, and realised that's just the default way items are referred to in minecraft so why it's causing an error here, or what parser is failing to extract the location correctly, I have no idea. My few hours on a singleplayer magistuarmory-only world has not had this issue yet.

For BionicFish, if you can find a way to remove the crashing mob (possibly nbt editing, or if you have a moment to set the world to peaceful before it crashes), you should be able to return to how things were.

**Comment by Magistu** [comment]
the issue is on rotten creatures mod side
