### ISSUE TITLE
Idea:Rapier 

### ISSUE THREAD

**Issue by PastelOrchid** [Magistu/Epic-Knights#22]
### Steps to Reproduce

i know this isn't and bug but i was thinking that the Rapier could make a interesting addition to this mod, seeing how they are there are famous for being used in the medieval era, I think it would also be cool if their attack speed was more than their damage and they could do more damage to the chainmail types armor 

### Expected Behavior

idk

### Actual Behavior

idk

### Your Minecraft version

hopefully 1.20 but would be nice in past versions to 

### Your error log

idk

### Additional Comments

I think it could be a cool addition to the mod 

### Conclusion

- [X] I agree that I am inattentively reading the description, just filling out everything

**Comment by Magistu** [comment]
hello PasterOrchid! check out epic knights addon project https://legacy.curseforge.com/minecraft/mc-mods/epic-knights-addon?__cf_chl_tk=pPrBcQIp2GZAufaxziBsqHwkQBmYDgiEzl3PEc8IKOk-1704381785-0-gaNycGzNE1A
