### ISSUE TITLE
Visual issue with the mod villager recruit

### ISSUE THREAD

**Issue by Veilleur1206** [Magistu/Epic-Knights#25]
### Steps to Reproduce

1. Use the mods : 
- architectury-9.2.14-forge.jar
- cloth-config-11.1.118-forge.jar
- [1.20.1-forge]-Epic-Knights-9.2.jar
- recruits-1.20.1-1.10.15.jar (villager recruits mod)

2. Open minecraft in version 1.20.1 (forge version : 47.2.21)

3. Hire a villager as a recruit (use the recruit spawn egg, then take emeralds in your inventory, click on the recruit and click on the button "HIRE"). Then place an helmet on his head (to open the recruit's inventory, shit click on him).

4. Observe that the top of the head and the nose stick out the helmet. (sometimes the eyes are not align with the helmet)

### Expected Behavior

The helmet should be on the right place, or totally hide the head.

### Actual Behavior

The top of the head and the nose stick out the helmet

### Your Minecraft version

1.20.1

### Your error log

https://gist.github.com/Veilleur1206/17ff2ec215238b95b674af7a6e392c66

### Conclusion

- [ ] I agree that I am inattentively reading the description, just filling out everything

**Comment by Magistu** [comment]
this is the issue of recruits mod as it doesn't support any modded 3d helmets. you should replace the model with a player by editing the recruits config
