### ISSUE TITLE
Steel plate is incompatible with steel plates from other mods.

### ISSUE THREAD

**Issue by ToatyBread** [Magistu/Epic-Knights#3]
I am playing a modpack that uses several mods that add steel and steel plates into the game.
These mods are
Mekanism,
Thermal Foundation,
and Immersive Engineering.
The steel plate recipe of these other mods overwrites the one from this mod so I am unable to craft certain armors.
Another strange thing is that around half of the knight armor recipes use the steel plate from this mod, but others use the other steel plate from the other mods.

**Comment by itzme1on** [comment]
I reported this bug to @Magistu 
This will be fixed in the next update 😄
