### ISSUE TITLE
Having Epic Knights Installed Causes a Crash When Applying a Banner Pattern to a Supplementaries Flag in a Loom

### ISSUE THREAD

**Issue by Anonagonn** [Magistu/Epic-Knights#35]
### Steps to Reproduce

Mods and versions: 
supplementaries-1.20-2.8.14
moonlight-1.20-2.11.33-forge
[1.20.1-forge]-Epic-Knights-9.8

Steps to reproduce:
•Place a Supplementaries flag into the loom with any banner pattern (both modded and vanilla patterns caused a crash)
•Place any dye into the loom to complete the recipe
•The game will crash trying to load a preview of the flag

### Expected Behavior

The banner is applied to the Supplementaries flag

### Actual Behavior

The game crashes

### Your Minecraft version

1.20.1-FORGE

### Your error log

Crash log: https://pastebin.com/5xBmaK2h; latest.log: https://gist.github.com/Anonagonn/be3584331e5dcc1c64739292c9e9794a

### Additional Comments

Copying a banner pattern onto a flag by combining it with an existing banner that utilizes that pattern does not cause a crash

### Conclusion

- [ ] I agree that I am inattentively reading the description, just filling out everything

**Comment by Anonagonn** [comment]
I also opened a ticket on the Supplementaries github and had a dialogue with a developer, the information there will probably prove useful to identifying the issue
https://github.com/MehVahdJukaar/Supplementaries/issues/1068

**Comment by Magistu** [comment]
will be fixed in the next update

**Comment by Magistu** [comment]
fixed
