### ISSUE TITLE
Invalid Player Data when importing from vanilla world

### ISSUE THREAD

**Issue by WhasianCactus** [Magistu/Epic-Knights#37]
### Steps to Reproduce

1. Create a World on Aternos as a vanilla server with plugins
2. Import said World file into a Fabric Server with these mods

Too Many Paintings 
RightClickToHarvest
MouseTweaks
Macaw Lights
Macaw Fences
Macaw Doors
JourneyMap
JEI
Jamlib
Him
FriendsAndFoes
Fabric API
Cloth Config
Architectury
Anvil Never Too Expensive 
Epic Nights

3. Start Server
4. Join Server and Recieve Invalid Player Data

### Expected Behavior

Join the Server without issue

### Actual Behavior

Displays cannot connect and Invalid Player Data

### Your Minecraft version

1.21

### Your error log

https://gist.github.com/WhasianCactus/02d65a210764e8cd952b3d320d6844ac 

### Conclusion

- [ ] I agree that I am inattentively reading the description, just filling out everything

**Comment by Magistu** [comment]
fixed in 9.13
