### ISSUE TITLE
Armet not craftable

### ISSUE THREAD

**Issue by UsernameNotActive** [Magistu/Epic-Knights#38]
### Steps to Reproduce

Fabric using version 9.8 of this mod for minecraft 1.20.1

### Expected Behavior

Able to craft Armet helmet

### Actual Behavior

No crafting recipe for Armet helmet.

### Your Minecraft version

1.20.1

### Your error log

no error is produced. 

### Additional Comments

This does not crash the game or causes an error. It's just that it is not possible to craft the Armet helmet in survival minecraft.

### Conclusion

- [X] I agree that I am inattentively reading the description, just filling out everything

**Comment by Magistu** [comment]
fixed
