### ISSUE TITLE
on 1.16.5 with epic fight the banners block the camera

### ISSUE THREAD

**Issue by LuigiPlayer1** [Magistu/Epic-Knights#5]
### Steps to Reproduce

enter the most recent 1.16.5 version of epic knights with the most recent version of epic fight 
put any banner on an armor 
go to epic fight fighting mode and go first person 
know your vison should be partially or totally obstructed 

### Expected Behavior

a fix or a thing i can do to mediate the situation 

### Actual Behavior

u can see it yourself on the steps to reproduce the big its very easy to reproduce

### Your Minecraft version

1.16.5

### Your error log

https://gist.github.com/LuigiPlayer1/d7929a3cc02fb28b82e9a659db466ab6

### Conclusion

- [ ] I agree that I am inattentively reading the description, just filling out everything

**Comment by LuigiPlayer1** [comment]
pls respond at least

**Comment by itzme1on** [comment]
Sorry for the long answer. I am very busy studying and working. I advise you to use Better Combat instead of Epic Knight. This error is independent of Epic Knight.
