### ISSUE TITLE
Server Crashes on PlayerLoggedInEvent.

### ISSUE THREAD

**Issue by ly-schneider** [Magistu/Epic-Knights#6]
I added some mods a day ago but removed them again due to errors, but now the server crashes every time I want to join.
Here is the start log (selfmade)(It also generates error message in the start log):
https://pastebin.com/6y8cXMRM
And here is the crash log:
https://pastebin.com/89WHm2Sb

In the crash log are also the mods listed.

It worked perfectly fine before, but now it gives those errors and I can't event join or remove Epic Knights to resolve the issue.

### Expected Behavior

I expected to just being able to play again normally.

### Actual Behavior

The server always crashes on login.

### Your Minecraft version

Minecraft 1.19.2 Forge

### Your error log

https://gist.github.com/ly-schneider/923e9ba18f967d8d0ee97e3974a0843d

### Conclusion

- [X] I agree that I am inattentively reading the description, just filling out everything

**Comment by itzme1on** [comment]
The error does not occur because of Epic Knight. It arises because of the Sophisticated Backpacks mod.

**Comment by ly-schneider** [comment]
Oh okay, thank you. Could you possibly explain? I'm pretty new to Minecraft modded. 
I saw the error messages at the start with: `[Worker-Main-2/ERROR] [net.minecraft.tags.TagLoader/]: Couldn't read tag list magistuarmory:pattern_item/bronze_kiteshield from magistuarmory:tags/banner_pattern/pattern_item/bronze_kiteshield.json in data pack [1.19]-Epic-Knights-Armor-and-Weapons-6.3v.jar ...` and thought that the error was from Epic Knights. 
But I couldn't resolve the error from the EventBus: `[net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: PACKET_HANDLER
	Index: 9
	Listeners:
		0: HIGH
		1: ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		2: NORMAL
		3: net.mine ...` and thought you could help.
