### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Pan-Etsu** [Magistu/Epic-Knights#7]
### Steps to Reproduce

I have found a bug. I am playing on version 1.19.2 Fabric and using the latest version of this mod for this version. I have been using the "Steel Ranseur" weapon and noticed that sometimes after attacking, my mouse seems to get stuck or unresponsive, but after several tests, I have determined that it is not a problem with my mouse, at least I believe so.

The essence of the bug is that sometimes, after attacking a mob, I continue the attack action, like hitting the ground to dig, untell i click. This problem occurs frequently with a variety of weapons, making it a bit challenging to play.

how to reproduce the error?
Easy, just keep attacking the mobs with the Steel Catcher weapon and after a period of time this error will appear. This kind of testing should be done with every weapon that has an additional "range" stat, I think so

### Expected Behavior

Do not continue digging the ground or other blocks after attacking.

### Actual Behavior

continue digging the ground or other blocks after attacking.

### Your Minecraft version

Minecraft 1.19.2 Fabric 

### Your error log

https://gist.github.com/Pan-Etsu/ef64425ddf58e119794cb856ac13d63a

### Additional Comments

I believe in you ! you can solve this bug :D

### Conclusion

- [X] I agree that I am inattentively reading the description, just filling out everything

**Comment by BlackAures1** [comment]
Same for 1.19.2 Forge with all weapons. Very annoying.

**Comment by Magistu** [comment]
hello thank you all for the report. I'll take my uni exams (сессия) and then I'll fix it so just stay tuned for the next update

**Comment by Pan-Etsu** [comment]
Бажаю успіхів друже !

**Comment by Magistu** [comment]
fixed in v8.1

**Comment by BlackAures1** [comment]
yay
