### ISSUE TITLE
what mods are for servers?

### ISSUE THREAD

**Issue by KimiQ83** [Magistu/Epic-Knights#9]
### Steps to Reproduce

Hello, a question, how do I know that the mods are for servers?

### Expected Behavior

all excellent

### Actual Behavior

all excellent

### Your Minecraft version

1.12.5

### Your error log

all excellent

### Additional Comments

I really like the mod

### Conclusion

- [ ] I agree that I am inattentively reading the description, just filling out everything

**Comment by itzme1on** [comment]
This is server side mod. No need to open issue for common questions. You can ask your question on [Epic Knights' Discord server](https://discord.gg/G9sWDYv4Pj).
